// shipping.message.ts
export const SHIPPING_MESSAGE_TYPE = {
  ADDRESS_SELECTED: "SHIPPING_ADDRESS_SELECTED",
  ADDRESS_CREATED: "SHIPPING_ADDRESS_CREATED",
  ADDRESS_UPDATED: "SHIPPING_ADDRESS_UPDATED",
} as const;
