export const NEW_ARRIVALS_DATA = [
  {
    id: 1,
    title: "실크 넥타이 1",
    price: 45000,
    image: "/images/item/tie1.png",
  },
  {
    id: 2,
    title: "실크 넥타이 2",
    price: 45000,
    image: "/images/item/tie2.png",
  },
  {
    id: 3,
    title: "실크 넥타이 3",
    price: 45000,
    image: "/images/item/tie3.png",
  },
  {
    id: 4,
    title: "실크 넥타이 4",
    price: 45000,
    image: "/images/item/tie4.png",
  },
  {
    id: 5,
    title: "실크 넥타이 5",
    price: 45000,
    image: "/images/item/tie5.png",
  },
  {
    id: 6,
    title: "실크 넥타이 6",
    price: 45000,
    image: "/images/item/tie6.png",
  },
  {
    id: 7,
    title: "실크 넥타이 7",
    price: 45000,
    image: "/images/item/tie7.png",
  },
  {
    id: 8,
    title: "실크 넥타이 8",
    price: 45000,
    image: "/images/item/tie8.png",
  },
  {
    id: 9,
    title: "실크 넥타이 9",
    price: 45000,
    image: "/images/item/tie9.png",
  },
  {
    id: 10,
    title: "실크 넥타이 10",
    price: 45000,
    image: "/images/item/tie10.png",
  },
  {
    id: 11,
    title: "실크 넥타이 11",
    price: 45000,
    image: "/images/item/tie11.png",
  },
  {
    id: 12,
    title: "실크 넥타이 12",
    price: 45000,
    image: "/images/item/tie12.png",
  },
  {
    id: 13,
    title: "실크 넥타이 13",
    price: 45000,
    image: "/images/item/tie13.png",
  },
  {
    id: 14,
    title: "실크 넥타이 14",
    price: 45000,
    image: "/images/item/tie14.png",
  },
  {
    id: 15,
    title: "실크 넥타이 15",
    price: 45000,
    image: "/images/item/tie15.png",
  },
  {
    id: 16,
    title: "실크 넥타이 16",
    price: 45000,
    image: "/images/item/tie16.png",
  },
  {
    id: 17,
    title: "실크 넥타이 17",
    price: 45000,
    image: "/images/item/tie17.png",
  },
  {
    id: 18,
    title: "실크 넥타이 18",
    price: 45000,
    image: "/images/item/tie18.png",
  },
  {
    id: 19,
    title: "실크 넥타이 19",
    price: 45000,
    image: "/images/item/tie19.png",
  },
  {
    id: 20,
    title: "실크 넥타이 20",
    price: 45000,
    image: "/images/item/tie20.png",
  },
];
