import type { Product } from "../types/product";

export const PRODUCTS_DATA: Product[] = [
  {
    id: 1,
    code: "A1234567890",
    name: "실크 넥타이 1",
    likes: 100,
    price: 45000,
    image: "/images/item/tie1.png",
    category: "formal",
    color: "navy",
    pattern: "solid",
    material: "silk",
  },
  {
    id: 2,
    code: "A1234567891",
    name: "실크 넥타이 2",
    likes: 100,
    price: 52000,
    image: "/images/item/tie2.png",
    category: "business",
    color: "blue",
    pattern: "stripe",
    material: "silk",
  },
  {
    id: 3,
    code: "A1234567892",
    name: "실크 넥타이 3",
    likes: 100,
    price: 48000,
    image: "/images/item/tie3.png",
    category: "formal",
    color: "black",
    pattern: "solid",
    material: "silk",
  },
  {
    id: 4,
    code: "A1234567893",
    name: "실크 넥타이 4",
    likes: 100,
    price: 39000,
    image: "/images/item/tie4.png",
    category: "casual",
    color: "beige",
    pattern: "dot",
    material: "cotton",
  },
  {
    id: 5,
    code: "A1234567894",
    name: "실크 넥타이 5",
    likes: 100,
    price: 55000,
    image: "/images/item/tie5.png",
    category: "wedding",
    color: "silver",
    pattern: "paisley",
    material: "silk",
  },
  {
    id: 6,
    code: "A1234567895",
    name: "실크 넥타이 6",
    likes: 100,
    price: 42000,
    image: "/images/item/tie6.png",
    category: "business",
    color: "gray",
    pattern: "stripe",
    material: "polyester",
  },
  {
    id: 7,
    code: "A1234567896",
    name: "실크 넥타이 7",
    likes: 100,
    price: 68000,
    image: "/images/item/tie7.png",
    category: "formal",
    color: "wine",
    pattern: "solid",
    material: "silk",
  },
  {
    id: 8,
    code: "A1234567897",
    name: "실크 넥타이 8",
    likes: 100,
    price: 35000,
    image: "/images/item/tie8.png",
    category: "casual",
    color: "brown",
    pattern: "check",
    material: "cotton",
  },
  {
    id: 9,
    code: "A1234567898",
    name: "실크 넥타이 9",
    likes: 100,
    price: 58000,
    image: "/images/item/tie9.png",
    category: "wedding",
    color: "silver",
    pattern: "solid",
    material: "silk",
  },
  {
    id: 10,
    code: "A1234567899",
    name: "실크 넥타이 10",
    likes: 100,
    price: 47000,
    image: "/images/item/tie10.png",
    category: "business",
    color: "navy",
    pattern: "dot",
    material: "silk",
  },
  {
    id: 11,
    code: "A1234567900",
    name: "실크 넥타이 11",
    likes: 100,
    price: 41000,
    image: "/images/item/tie11.png",
    category: "casual",
    color: "blue",
    pattern: "check",
    material: "cotton",
  },
  {
    id: 12,
    code: "A1234567901",
    name: "실크 넥타이 12",
    likes: 100,
    price: 75000,
    image: "/images/item/tie12.png",
    category: "formal",
    color: "black",
    pattern: "paisley",
    material: "silk",
  },
  {
    id: 13,
    code: "A1234567902",
    name: "실크 넥타이 13",
    likes: 100,
    price: 32000,
    image: "/images/item/tie13.png",
    category: "casual",
    color: "beige",
    pattern: "stripe",
    material: "polyester",
  },
  {
    id: 14,
    code: "A1234567903",
    name: "실크 넥타이 14",
    likes: 100,
    price: 62000,
    image: "/images/item/tie14.png",
    category: "wedding",
    color: "silver",
    pattern: "dot",
    material: "silk",
  },
  {
    id: 15,
    code: "A1234567904",
    name: "실크 넥타이 15",
    likes: 100,
    price: 49000,
    image: "/images/item/tie15.png",
    category: "business",
    color: "gray",
    pattern: "solid",
    material: "wool",
  },
  {
    id: 16,
    code: "A1234567905",
    name: "실크 넥타이 16",
    likes: 100,
    price: 38000,
    image: "/images/item/tie16.png",
    category: "casual",
    color: "brown",
    pattern: "stripe",
    material: "cotton",
  },
  {
    id: 17,
    code: "A1234567906",
    name: "실크 넥타이 17",
    likes: 100,
    price: 54000,
    image: "/images/item/tie17.png",
    category: "formal",
    color: "wine",
    pattern: "dot",
    material: "silk",
  },
  {
    id: 18,
    code: "A1234567907",
    name: "실크 넥타이 18",
    likes: 100,
    price: 46000,
    image: "/images/item/tie18.png",
    category: "business",
    color: "navy",
    pattern: "check",
    material: "silk",
  },
  {
    id: 19,
    code: "A1234567908",
    name: "실크 넥타이 19",
    likes: 100,
    price: 71000,
    image: "/images/item/tie19.png",
    category: "formal",
    color: "black",
    pattern: "stripe",
    material: "silk",
  },
  {
    id: 20,
    code: "A1234567909",
    name: "실크 넥타이 20",
    likes: 100,
    price: 43000,
    image: "/images/item/tie20.png",
    category: "casual",
    color: "blue",
    pattern: "solid",
    material: "cotton",
  },
];
