import { Product } from "../types/product";

export const PRODUCTS_DATA: Product[] = [
  {
    id: 1,
    title: "실크 넥타이 1",
    price: 45000,
    image: "/images/item/tie1.png",
    category: "formal",
    color: "navy",
    pattern: "solid",
    material: "silk",
    isNew: true,
  },
  {
    id: 2,
    title: "실크 넥타이 2",
    price: 52000,
    image: "/images/item/tie2.png",
    category: "business",
    color: "blue",
    pattern: "stripe",
    material: "silk",
    isNew: true,
  },
  {
    id: 3,
    title: "실크 넥타이 3",
    price: 48000,
    image: "/images/item/tie3.png",
    category: "formal",
    color: "black",
    pattern: "solid",
    material: "silk",
    isPopular: true,
  },
  {
    id: 4,
    title: "실크 넥타이 4",
    price: 39000,
    image: "/images/item/tie4.png",
    category: "casual",
    color: "beige",
    pattern: "dot",
    material: "cotton",
    isNew: true,
  },
  {
    id: 5,
    title: "실크 넥타이 5",
    price: 55000,
    image: "/images/item/tie5.png",
    category: "wedding",
    color: "silver",
    pattern: "paisley",
    material: "silk",
    isPopular: true,
  },
  {
    id: 6,
    title: "실크 넥타이 6",
    price: 42000,
    image: "/images/item/tie6.png",
    category: "business",
    color: "gray",
    pattern: "stripe",
    material: "polyester",
  },
  {
    id: 7,
    title: "실크 넥타이 7",
    price: 68000,
    image: "/images/item/tie7.png",
    category: "formal",
    color: "wine",
    pattern: "solid",
    material: "silk",
    isPopular: true,
  },
  {
    id: 8,
    title: "실크 넥타이 8",
    price: 35000,
    image: "/images/item/tie8.png",
    category: "casual",
    color: "brown",
    pattern: "check",
    material: "cotton",
  },
  {
    id: 9,
    title: "실크 넥타이 9",
    price: 58000,
    image: "/images/item/tie9.png",
    category: "wedding",
    color: "silver",
    pattern: "solid",
    material: "silk",
    isNew: true,
  },
  {
    id: 10,
    title: "실크 넥타이 10",
    price: 47000,
    image: "/images/item/tie10.png",
    category: "business",
    color: "navy",
    pattern: "dot",
    material: "silk",
    isPopular: true,
  },
  {
    id: 11,
    title: "실크 넥타이 11",
    price: 41000,
    image: "/images/item/tie11.png",
    category: "casual",
    color: "blue",
    pattern: "check",
    material: "cotton",
  },
  {
    id: 12,
    title: "실크 넥타이 12",
    price: 75000,
    image: "/images/item/tie12.png",
    category: "formal",
    color: "black",
    pattern: "paisley",
    material: "silk",
    isPopular: true,
  },
  {
    id: 13,
    title: "실크 넥타이 13",
    price: 32000,
    image: "/images/item/tie13.png",
    category: "casual",
    color: "beige",
    pattern: "stripe",
    material: "polyester",
  },
  {
    id: 14,
    title: "실크 넥타이 14",
    price: 62000,
    image: "/images/item/tie14.png",
    category: "wedding",
    color: "silver",
    pattern: "dot",
    material: "silk",
    isNew: true,
  },
  {
    id: 15,
    title: "실크 넥타이 15",
    price: 49000,
    image: "/images/item/tie15.png",
    category: "business",
    color: "gray",
    pattern: "solid",
    material: "wool",
    isPopular: true,
  },
  {
    id: 16,
    title: "실크 넥타이 16",
    price: 38000,
    image: "/images/item/tie16.png",
    category: "casual",
    color: "brown",
    pattern: "stripe",
    material: "cotton",
  },
  {
    id: 17,
    title: "실크 넥타이 17",
    price: 54000,
    image: "/images/item/tie17.png",
    category: "formal",
    color: "wine",
    pattern: "dot",
    material: "silk",
    isNew: true,
  },
  {
    id: 18,
    title: "실크 넥타이 18",
    price: 46000,
    image: "/images/item/tie18.png",
    category: "business",
    color: "navy",
    pattern: "check",
    material: "silk",
  },
  {
    id: 19,
    title: "실크 넥타이 19",
    price: 71000,
    image: "/images/item/tie19.png",
    category: "formal",
    color: "black",
    pattern: "stripe",
    material: "silk",
    isPopular: true,
  },
  {
    id: 20,
    title: "실크 넥타이 20",
    price: 43000,
    image: "/images/item/tie20.png",
    category: "casual",
    color: "blue",
    pattern: "solid",
    material: "cotton",
  },
];
